# Configuration file for Mega-Linter
# See all available variables at https://nvuillam.github.io/mega-linter/configuration/ and in linters documentation

SHOW_ELAPSED_TIME: true

ENABLE:
  - CPP
  - DOCKERFILE
  - MARKDOWN
  - PYTHON
  - YAML
ENABLE_LINTERS:
  - CPP_CPPLINT
  - DOCKERFILE_DOCKERFILELINT
  - MARKDOWN_MARKDOWNLINT
  - PYTHON_PYLINT
  - YAML_YAMLLINT
EXCLUDED_DIRECTORIES:
  - .venv
  - .git