# FROM mcr.microsoft.com/azure-functions/python:3.0-python3.8-appservice
FROM python:3.8-slim-buster as base

RUN pip install --upgrade pip

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

FROM base

COPY --from=base /opt/venv/ /opt/venv/

ENTRYPOINT [ "/bin/bash" ]
