name: Conditional

on:
  workflow_dispatch:
    inputs:
      push_images:
        description: 'Push to registry (yes/no)'
        required: true
        default: 'no'
  push:

jobs:
  conditional:
    name: Conditional
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        id: vars
        run: |
          if [ '${{ github.event.inputs.push_images }}' == 'yes' ]
            || ( [ '${{ github.ref }}' == 'refs/heads/main' ] && [ '${{ github.event_name }}' == 'push' ] )
            || ( [ '${{ github.ref }}' == 'refs/heads/dev' ] && [ '${{ github.event_name }}' == 'push' ] )
          then
            echo "::set-output name=push::yes"
          else
            echo "::set-output name=push::no"
          fi
        
      - name: Conditional
        run: |
          if [ '${{ steps.vars.outputs.push }}' == 'yes' ]
          then
            echo 'I will push'
          else
            echo 'I will NOT push'
          fi

