name: Conditional

on:
  workflow_dispatch:
    inputs:
      push_images:
        description: 'Push to registry (yes/no)'
        required: true
        default: 'no'
  push:
    branches:
      - main
      - dev



jobs:
  conditional:
    name: Conditional
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        id: vars
        run: |
          if [ '${{ github.event.inputs.push_images }}' == 'yes' ] ||
            ( [ '${{ github.ref }}' == 'refs/heads/main' ] && [ '${{ github.event_name }}' == 'push' ] )
          then
            echo "output=yes"
            echo "::set-output name=push::yes"
          else
            echo "output=no"
            echo "::set-output name=push::no"
          fi
        
      - name: Conditional
        run: |
          if [ '${{ steps.vars.outputs.push }}' == 'yes' ]
          then
            echo 'I will push'
          else
            echo 'I will NOT push'
          fi

