name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      simulate:
        description: 'useless quiestion'
        required: true
        default: 'yes'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      # # This is the a separate action that sets up buildx runner
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - run: bash build-image.sh "${{ github.repository_owner }}" "${{ secrets.CR_PAT }}" Dockerfile.base gha-base:latest

      - run: bash build-image.sh "${{ github.repository_owner }}" "${{ secrets.CR_PAT }}" Dockerfile.runner gha-runner:latest gha-base:latest
