name: Run Pytest

on: [push]

jobs:
  manual-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Test with pytest
        run: |
          pytest
