name: Run Unit tests

on:
  workflow_dispatch:
    inputs:
      push_images:
        description: 'Push to registry (yes/no)'
        required: true
        default: 'no'
  push:

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Test workflow
        run: |
          if [ '${{ github.event.inputs.push_images }}' == 'yes' ]
          then
            echo 'this is a yes'
          else
            echo 'this is a no'
          fi
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Test with pytest
        run: |
          pytest
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}