name: Run Unit tests

on:
  workflow_dispatch:
    inputs:
      push_images:
        description: 'Push to registry (yes/no)'
        required: true
        default: 'no'
  push:

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Test workflow
        run: |
          if [ '${{ github.event.inputs.push_images }}' == 'yes' ]
          then
            echo 'this is a yes'
          else
            echo 'this is a no'
          fi
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Test with pytest
        run: |
          pytest
      # - name: Slack Notification
      #   if: ${{ always() }}
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - uses: 8398a7/action-slack@v3
        with:
          github_base_url: https://your.ghe.com # Specify your GHE
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()