---

name: Build with version
on: [push]
jobs:
  build:
    name: Versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Get current tag
        id: tag
        run: echo "::set-output name=tag::$(git describe --exact-match --tags $(git log -n1 --pretty='%h'))"
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_DATE
        env:
          TAG_NAME: ${{ steps.tag.outputs.tag }}
          RELEASE_DATE: ${{ steps.date.outputs.date }}
      - name: Test with input
        uses: actions/hello-world-docker-action@master
        with:
          who-to-greet: Version ${{ steps.tag.outputs.tag }} ${{ steps.date.outputs.date }}
